// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_seq_tn5_bias_par
NumericVector get_seq_tn5_bias_par(std::string genome, DataFrame bias_table);
RcppExport SEXP _tn5bias_get_seq_tn5_bias_par(SEXP genomeSEXP, SEXP bias_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type genome(genomeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type bias_table(bias_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(get_seq_tn5_bias_par(genome, bias_table));
    return rcpp_result_gen;
END_RCPP
}
// get_seq_tn5_bias
NumericVector get_seq_tn5_bias(std::string genome, DataFrame bias_table);
RcppExport SEXP _tn5bias_get_seq_tn5_bias(SEXP genomeSEXP, SEXP bias_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type genome(genomeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type bias_table(bias_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(get_seq_tn5_bias(genome, bias_table));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tn5bias_get_seq_tn5_bias_par", (DL_FUNC) &_tn5bias_get_seq_tn5_bias_par, 2},
    {"_tn5bias_get_seq_tn5_bias", (DL_FUNC) &_tn5bias_get_seq_tn5_bias, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tn5bias(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
