# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_seq_tn5_bias <- function(genome, bias_table) {
    .Call(`_tn5bias_get_seq_tn5_bias`, genome, bias_table)
}

get_seq_tn5_bias_par <- function(genome, bias_table) {
    .Call(`_tn5bias_get_seq_tn5_bias_par`, genome, bias_table)
}

